// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hdmtifhpocjjerlijiby.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhkbXRpZmhwb2NqamVybGlqaWJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyMjAxMzEsImV4cCI6MjA1ODc5NjEzMX0.S-54U1h5oc4o6iw1RojX4-YFl5DkmZMjCmZSvOdWg54";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);